import Head from "next/head";
import { Box } from "@chakra-ui/react";
import styles from "@/styles/Home.module.css";
import { Navbar, Intro, Resume, AboutMe } from "@/Components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ayaz's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box w="100%">
          <Navbar />
          <Intro />
          <AboutMe />
          <Resume />
        </Box>
      </main>
    </>
  );
}
