import { useRef } from "react";
import Head from "next/head";
import { Box, useMediaQuery } from "@chakra-ui/react";
import styles from "@/styles/Home.module.css";
import {
  Navbar,
  Intro,
  Resume,
  AboutMe,
  CaseStidies,
  Contact,
} from "@/Components";
import { useState } from "react";
import {
  HomeSVG,
  AboutSVG,
  CaseStudySVG,
  ResumeSVG,
  ContactSVG,
} from "../Components/svg";

import { useScrollPosition } from "@/utils";

export interface INavbarAction {
  title: string;
  onClick: Function;
  icon?: JSX.Element;
}

export default function Home() {
  const scrollPosition = useScrollPosition();
  const [isLargerThan800] = useMediaQuery("(min-width: 900px)");

  const [navbarActions, updateNavBarActions] = useState([
    {
      title: "Home",
      icon: <HomeSVG />,
      onClick: () => handleIntroClick(),
    },
    {
      title: "About Me",
      icon: <AboutSVG />,
      onClick: () => handleAboutClick(),
    },
    {
      title: "Resume",
      icon: <ResumeSVG />,
      onClick: () => handleResumeClick(),
    },
    {
      title: "Case Studies",
      icon: <CaseStudySVG />,
      onClick: () => handleCaseStudiesClick(),
    },
    {
      title: "Contact Me",
      icon: <ContactSVG />,
      onClick: () => handleContactClick(),
    },
  ]);

  const introRef = useRef(null);
  const aboutRef = useRef(null);
  const resumeRef = useRef(null);
  const caseStudiesRef = useRef(null);
  const contactRef = useRef(null);

  const handleAboutClick = () => {
    // @ts-ignore
    aboutRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleIntroClick = () => {
    // @ts-ignore
    introRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleResumeClick = () => {
    // @ts-ignore
    resumeRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleCaseStudiesClick = () => {
    // @ts-ignore
    caseStudiesRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleContactClick = () => {
    // @ts-ignore
    contactRef.current.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <title>Ayaz's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box w="100%">
          <Navbar
            navbarActions={navbarActions}
            scrollPosition={scrollPosition}
            isLargerThan800={isLargerThan800}
          />
          <Intro introRef={introRef} />
          <AboutMe scrollPosition={scrollPosition} aboutRef={aboutRef} />
          <Resume scrollPosition={scrollPosition} resumeRef={resumeRef} />
          <CaseStidies
            scrollPosition={scrollPosition}
            caseStudiesRef={caseStudiesRef}
          />
          <Contact scrollPosition={scrollPosition} contactRef={contactRef} />
        </Box>
      </main>
    </>
  );
}
